services:
  weaponsforge.adventofcode-dev:
    container_name: weaponsforge-adventofcode-dev
    image: weaponsforge/adventofcode:dev
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    ports:
      - "9229:9229"
    stdin_open: true
    tty: true
